name: Auto Gen

on:
  schedule:
    - cron:  '0 7 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pillow
    - name: Generating Steam Sign
      env:
        SteamID: ${{ secrets.SteamID }}
        small: ${{ secrets.small }}
      run: |
        python steamsign.py $SteamID $small
    - name: Git Commit
      run: |
        git add -A .
        git config --local user.email "$GitEmail"
        git config --local user.name "$GitName"
        git commit -am "update"
      env:
        GitEmail: ${{ secrets.GitEmail }}
        GitName: ${{ secrets.GitName }}
    - name: Git Push
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
